# Generated by Django 5.2.3 on 2025-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hero/')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
