# Generated by Django 5.2.3 on 2025-06-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='btn_text',
            field=models.CharField(default='Get in touch', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='btn_url',
            field=models.CharField(default='contactus', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(default='I specialize in crafting intuitive digital experiences...'),
        ),
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Rakhmanberdi Izbassar', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='typing_delay_1',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='hero',
            name='typing_delay_2',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='hero',
            name='typing_text_1',
            field=models.CharField(default="I'm a Full-Stack Developer", max_length=255),
        ),
        migrations.AddField(
            model_name='hero',
            name='typing_text_2',
            field=models.CharField(default="I'm a UI/UX Designer", max_length=255),
        ),
    ]
