# Generated by Django 5.2.3 on 2025-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hero_btn_text_hero_btn_url_hero_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('iconBgClass', models.CharField(max_length=100)),
                ('href', models.URLField()),
            ],
        ),
    ]
